### ISSUE TITLE
Repository mirror

### ISSUE THREAD

**Issue by ThatOneCalculator** [ClaraCrazy/Flipper-Xtreme#132]
Since Github already put a content warning(!) on this repo, I think it'd be a good idea to put it on a Gitea/Forgejo mirror in case Github takes it down

**Comment by ClaraCrazy** [comment]
Github put this warning there because I told it to, as I dont want 13yr old kids ad an audience

1. This isnt a toy. Well, it kinda is but not for kids

2. The nsfw asset pack literally contains my own body. I dont want to be the first content of such sorts a kid sees

3. Some of the files we did, or still do, host / distribute arent for kids either. Like the fact we allow people to sync some rolling-code based garage doors etc. (No cars.. no drama pls) 

I appreciate the concern, but we are in no need for a mirror, and if we did, I always have a copy of all my projects on my selfhosted cloud network

~ Clara
