### ISSUE TITLE
Crash on idle - null pointer dereference

### ISSUE THREAD

**Issue by TheMany172** [ClaraCrazy/Flipper-Xtreme#246]
### Describe the bug.

In response to notice on discord - firmware-updates asking to be told if this happens

Clara:
"Mobile app is fixed. If you experience crashes in idle, please let us know. Its important. We're working with UL & OFW to get deepsleep stable. Community effort that will pay off."

happy to help, if that is possible

### Reproduction

not sure exactly how to recreate or what info would be of use

I turned it on an hour or so ago - when i came  back to my desk it had the

'flipper crashed but has been rebooted, null pointer dereference'

**Comment by ClaraCrazy** [comment]
Please message us on discord. The issue is something we technically arent even allowed to publicly talk about (yet), not caused by firmware. Thats all I am able to say here unfortunately.

**Comment by TheMany172** [comment]
oh ok, fair enough - will close

**Comment by CapuchaRojo** [comment]
Yes ma’am there is more. I may flash things wrong.
iOs..

Sometimes when running the apps straight from your new gooey system wii icons, Wi-Fi folder, I will only generate the 160+ pages  log of repetitive bad heading error.

I have Apple devices
Own 13promax and iPad gen 10.
I have access to a MacBook which makes life easier with aurduino and terminal and the usually reliable GitHub web updaters.

But I’ll let you see what iOS is doing to me: pics attached
I’ve spoke with skelli briefly on it. All his stuff worked except step 0 for mac, but I got it to work anyhow somehow with his release. 🤷‍♂️ I’m just going thru all the available avenues to flash my boards.

I have multiple issues but figured I would start with this one.

Thank you for helping me btw
It is much appreciated. And since not in discord with ya anymore I know u doing this is beyond. So after done, I will shoot u patreon style loving for sure.

Thanks again

Sent with Spark

**Comment by ClaraCrazy** [comment]
*confused clara noises*

**Comment by CapuchaRojo** [comment]
Basically
I couldn’t get the flash for the life of me and when I finally did it didn’t do all the steps correctly 100%. There is a step zero for Mac that I couldn’t get accomplished. It was a download for -r required

But I was told I was over complicating it by Skell and that if it’s not found it’s not found

But then I can not run the maurader without getting the errors in the pics.
Error- invalid header: 0xe0ffd8ff
Ran 1165 times.

Sent with Spark

**Comment by ClaraCrazy** [comment]
has nothing to do with the issue.

**Comment by CapuchaRojo** [comment]
Well. Ok. Giving u possible issues that come before it

Sent with Spark

**Comment by CapuchaRojo** [comment]
Messaged to CC but couldn’t find themany172

**Comment by JustThisGuyJoe** [comment]
Hey Clara, I capture some profiles for an overhead fan for you to include on your next release. 
https://github.com/JustThisGuyJoe/RF-Profiles Please don't cite me or credit me in any way, just throw them in there, I'm a private person who values my anonymity.
