### ISSUE TITLE
removing the credits animation

### ISSUE THREAD

**Issue by sariyan-0** [ClaraCrazy/Flipper-Xtreme#255]
### Describe the enhancement you're suggesting.

Hi, there, How are you? I had a question about the extreme software by Clara Crazy and I have a little problem with it the thing is that every time I'm trying to use my flipper with the extreme software I have on it im keep seeing the name of the team that created the software instead of the dolphin's animation on the SFW mode and I want to delete the creator animation because it's very annoying so can you guys give me a tutorial how to remove it because I know how to delete animations but i don't wanna delete the wrong one I would really appreciate it if you help me with this

**Comment by Willy-JL** [comment]
disable the fallback animation in settings

**Comment by GreenGinkgo** [comment]
"Fallback Anim" is set to OFF and the "Huge thanks to my team" scroller still appears
XFW-0046

**Comment by Willy-JL** [comment]
your flipper is angry at you, and it is low level, so it doesnt find another suitable animation to play. this behavior has changed in dev branch and will be fixed in next release, so it ignores the angriness of flipper and only unlocks animations based on level, so this situation cant happen

**Comment by sariyan-0** [comment]
Can you give me a more precise information

**Comment by Willy-JL** [comment]
> Can you give me a more precise information

@sariyan-0 i gave you very clear information, you just refuse to understand. i will explain it all ONE LAST TIME, then ill start deleting your comments. also you are posting in 2 different issues, i dont know what you are even asking about anymore. you should stop replying from email and log into github from a browser, you are just making this confusing for yourself.

flipper has a butthurt value, this value increases periodically (you decide how often with the butthurt timer option in xtreme settings) making your flipper angry. using your flipper makes the butthurt value go down, so it becomes happy again. since your flipper is angry, you can disable the butthurt timer (or set it to a high value like 48 hours) and keep using it, after using it for some time IT WILL BECOME HAPPY AGAIN, stop asking how to make it happy, this is how you do it. just use it and shut up.

as for the credits animation, you can disable it in xtreme settings > interface > graphics > fallback anim, this will stop it from showing randomly. if it still shows up, as i explained in the comment above, it is because the current release has a problem with the mood, where if your flipper is angry, sometimes the only animation that shows is the credits animation.

now stop commenting. you have way more information than you needed, please shut up.
