### ISSUE TITLE
Bluetooth cloner

### ISSUE THREAD

**Issue by Zarcolio** [ClaraCrazy/Flipper-Xtreme#259]
### Describe the enhancement you're suggesting.

Like the Evil Twin attack for wifi, I'd like to have a Bluetooth cloner that clones the name and MAC address from a Bluetooth device in range. It creates a list of all Bluetooth devices the Flipper sees and allows the user to select a device to clone name and MAC to the Flipper.

Hopefully an unsuspecting Bluetooth user connects to the wrong Bluetooth device and allows the Flipper to attack the device with BadKB over Bluetooth.

**Comment by Willy-JL** [comment]
not possible unfortunately.

1: cant list nearby devices as flipper doesn't see the other devices, its the other devices that see flipper. this is because flipper uses the BLE lite stack, which only supports acting as the 'slave' device and not the 'master' device.

2: paired devices wouldn't automatically connect to the spoofed device in most cases since the devices most likely have different appearances (flipper acts as a bluetooth keyboard in badkb, while the device you're impersonating might be something like a speaker, the target device would see this discrepancy and would refuse to automatically connect, or it would connect but not work as a keyboard making it useless)

you can go in and manually change the bluetooth name if you want however, thats the closes youll get
