### ISSUE TITLE
Xtreme Settings: Fix battery icon style not saving

### ISSUE THREAD

**Issue by Anatejl** [ClaraCrazy/Flipper-Xtreme#286]
### Describe the bug.

After reboot any different style of charge bar falls back to one with number in it.
[Video](https://cdn.discordapp.com/attachments/368580551445315586/1114666507729911928/IMG_0591.mov)

Pics: 
![image](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/61248428/cf17f900-a7a5-4a0e-873e-db7d66940e86)
![image](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/61248428/a8948978-8287-4ef6-b6c3-f28c54a37a71)

### Reproduction

1. Set different battery icon style.
2. Reboot

### Target

X48

**Comment by Willy-JL** [comment]
can confirm this, will be fixed soon

**Comment by Anatejl** [comment]
Thank you! 
Can I ask a bit about backstage. Saw your commit, is it because of mismatch of variable types? 
As for fix, uint32_t is now in header instead of settings.c. 
It affected in the way, that changes to the battery wasn't saved, and of doing so is being reset on reboot?

**Comment by Willy-JL** [comment]
storing the variable as an enum type apparently caused issues when going to save that value, instead of saving the enum value as 0-6, it overflowed somewhere and got to 65k+ or something like that. you can open the settings file and see for yourself. it resets to the default because when reading the setting it reads that 65k value, which is out of bouds of the 0-6, so it rounds down to 6, which happens to be the bar percent and also the default value
