### ISSUE TITLE
BadKB: Handle USB and BT connections separately (allow using qFlipper / Mobile App)

### ISSUE THREAD

**Issue by DarkEnder4583** [ClaraCrazy/Flipper-Xtreme#291]
### Describe the bug.

When using remote control on the flipper, it will disconnect from your phone the moment you open BadKB.

I imagine this is due to the limitations of the Bluetooth chip, but stopping this from happening when using BadKB for its USB protocol would be nice.

### Reproduction

1. Connect to the flipper through the mobile app
2. Begin remote control 
3. Navigate over to BadKB and attempt to run it

**Comment by Willy-JL** [comment]
yes, its because when you open badkb it preps both usb and bt connections modes. a good majority of the issues we had over time with backb were exactly because that was not the case. it is possible to initialize them separately, but its not the case right now and it needs to be implemented carefully to avoid more problems. we have this already planned in our todo list (check the projects tab)

**Comment by DarkEnder4583** [comment]
Gotcha. Thank you for the information!

**Comment by Willy-JL** [comment]
Now implemented via 81f42afed0474a4c580ff698563c072eeab1b58a

please let us know how it goes by either flashing the latest dev branch, or join the discord server so i can add you to a ticket with a precompiled build you can try

**Comment by DarkEnder4583** [comment]
I know this has already been marked as completed, but I just wanted to say it works for me now! Sorry for the late response, and thank you for your work!
