### ISSUE TITLE
XFW-0048_03062023 Update. Tamagotchi not working anymore.

### ISSUE THREAD

**Issue by zcbml88** [ClaraCrazy/Flipper-Xtreme#294]
### Describe the bug.

I am updating from firmware version XFW-0046_06052023. There is a blank screen when I load and try to play Tamagotchi.. The Flipper freezes and the only way to get the flipper working again is to do a hard reboot. 
Recently I just tried downgrading from XFW-48 back to XFW-46 and I have my Tamagotchi back up and running with my saved progress. I would be nice to have the new update though..

### Reproduction

1: Launch Game
2:Flipper freezes

### Anything else?

Does anyone else have this problem?

**Comment by ClaraCrazy** [comment]
not our app, open an issue with the creator of that external app plwase

**Comment by Apok76** [comment]
Couldn’t this be along the same lines as the Xtreme firmware not Syncing correctly a couple of versions ago. You fixed that in the firmware. Or am I mistaken?

-Adam Cloud
________________________________

**Comment by ClaraCrazy** [comment]
? this makes no sense lol.

This app is not written by us, unleashed & rm have the same issue with it, bc the app developer doesnt work on it.

We develop a pentesting firmware, not cringy ahh games for it, so I really dont care about it not working. If it wont be fixed by the dev, the app will just be removed

**Comment by Apok76** [comment]
Thanks for the explanation. I was wrong once before. Thanks for number 2.

Love the firmware. You rock.

-Adam Cloud
________________________________
