### ISSUE TITLE
is it possible to enable nfc on u2f ?

### ISSUE THREAD

**Issue by trisosamu** [ClaraCrazy/Flipper-Xtreme#42]
### Description of the feature you're suggesting.

![p8jm40x6l8w91](https://user-images.githubusercontent.com/78987040/209925499-a3a6602d-0344-4187-b132-f10987fceece.jpg)

**Comment by ClaraCrazy** [comment]
This would be a feature request to bring up at OFW as I'm just a single developer and barely have the time to work on all the stuff I need for this to work, lol.

Feel free to open a PR if you know how to do this tho. Otherwise, it will exist here as soon as it exist in OFW

Thanks for using our Firmware, feel free to join the Discord!
